version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sociopath-api
    ports:
      - "5004:5000"         # API доступен снаружи
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:secret@localhost:3306/sociopath?schema=public
      - PORT=5000
    depends_on:
      - mysql
    restart: unless-stopped

  redis:
    image: redis
    container_name: sociopath_mono_redis
    ports:
      - "6379:6379"


  mysql:
    image: mysql:8.0
    container_name: sociopath_mono_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sociopath
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

